// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Url struct {
	HashID    string    `json:"hash_id"`
	Url       string    `json:"url"`
	ExpiresAt time.Time `json:"expires_at"`
}
