// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: urls.sql

package db

import (
	"context"
)

const createUrl = `-- name: CreateUrl :one
INSERT INTO urls (
  hash_id,
  url
) VALUES (
  $1,
  $2
) RETURNING hash_id, url
`

type CreateUrlParams struct {
	HashID string `json:"hash_id"`
	Url    string `json:"url"`
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createUrl, arg.HashID, arg.Url)
	var i Url
	err := row.Scan(&i.HashID, &i.Url)
	return i, err
}

const getUrlByHashId = `-- name: GetUrlByHashId :one
SELECT hash_id, url FROM urls WHERE hash_id=$1
`

func (q *Queries) GetUrlByHashId(ctx context.Context, hashID string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getUrlByHashId, hashID)
	var i Url
	err := row.Scan(&i.HashID, &i.Url)
	return i, err
}
